### ISSUE TITLE
issus

### ISSUE THREAD

**Issue by ivan19871002** [mi3-dev/android_device_xiaomi_cancro#4]
<3>[ 1677.002404] Freezing of user space  aborted
<4>[ 1677.002421] 
<4>[ 1677.002432] Restarting tasks ... done.
<6>[ 1677.008021] PM: suspend exit 2014-08-28 01:27:41.917197295 UTC
<6>[ 1677.008044] PM: suspend lasts 0 seconds
<6>[ 1677.065782] PM: suspend entry 2014-08-28 01:27:41.974959794 UTC
<6>[ 1677.065798] PM: Syncing filesystems ... done.
<4>[ 1677.098159] Freezing user space processes ... 
<6>[ 1677.108854] active wakeup source: qcom_rx_wakeloc

I think something cant sleep.

**Comment by varunchitre15** [comment]
Push your fixes to a different branch, I will look into it. I don't have
any of the issues but pressure and sound sensor doesn't work with my fix.

**Comment by ivan19871002** [comment]
close , I use network adb .

**Comment by ivan19871002** [comment]
I use the private source for sensors with frameworks/base and native , I dont modify anything with devices

**Comment by varunchitre15** [comment]
Well in that case that's not a fix, is it?
It won't be accepted into official cm release wherever we attempt to get
one.
As I said you can upload the patch to gist I will see whether it can be
converted to device tree patch.

**Comment by ivan19871002** [comment]
I cant upload it ,because it is a private source .  I try to converte

**Comment by varunchitre15** [comment]
Not source. I am asking for commit, git show "commit-hash" > ~/fix.patch
