### ISSUE TITLE
Dynamic ro.product.model for Mi3w and Mi4w

### ISSUE THREAD

**Issue by jrizzoli** [mi3-dev/android_device_xiaomi_cancro#5]
I'm adding a "dynamic" ro.product.model since both Mi4 and Mi3 (WCDMA) are cancro. Can you provide me the output of 
cat /sys/devices/system/soc/soc0/raw_id
Tell me if Mi 3W or Mi 4W please

**Comment by varunchitre15** [comment]
Mi4 is not cancro. It is "Leo"

**Comment by jrizzoli** [comment]
Mi4w is

**Comment by ivan19871002** [comment]
cmdline    ro.hwversion  = 3x  is mi3    = 4x  is mi4
